export {
  registrationEmail,
  emailVerificationEmail,
  orderConfirmationEmail,
  kycSubmittedEmail,
  kycApprovedEmail,
  kycRejectedEmail,
  payoutRequestedEmail,
  payoutApprovedEmail,
  payoutRejectedEmail,
  ticketCreatedEmail,
  ticketRepliedEmail,
  affiliateSignupEmail,
  affiliatePayoutUpdateEmail,
  newsletterSubscriptionEmail,
} from './email-templates';
